#![allow(
    clippy::unwrap_used,
    clippy::doc_markdown,
    clippy::doc_lazy_continuation,
    clippy::needless_borrows_for_generic_args,
    clippy::needless_pass_by_value,
    clippy::similar_names,
    clippy::unnecessary_cast,
    clippy::manual_range_contains,
    clippy::iter_cloned_collect,
    clippy::explicit_deref_methods,
    clippy::explicit_auto_deref,
    clippy::too_many_lines
)]
//! Integration tests for `cacg_ingest::extract_pages` against the
//! committed parity-corpus PDF fixtures.
//!
//! These tests exercise the live `pdfium-render` runtime binding and
//! therefore require `libpdfium` to be discoverable on the system.
//! When `libpdfium` is absent each test prints a "skipping" notice
//! and returns successfully, keeping the suite green on runners
//! without the native dependency. To make a missing `libpdfium` a
//! hard failure (e.g. in CI), set `CACG_REQUIRE_PDFIUM=1` before
//! running `cargo test`.
//!
//! ## Test isolation: pdfium-render single-bind constraint
//!
//! pdfium-render's `Pdfium::bind_to_system_library()` may only be
//! called once per process; a second call asserts and the harness
//! SEGVs. This file is one of several pdfium-bound test files in
//! the workspace; running them all in one `cargo test` invocation
//! requires `--test-threads=1` so each test file gets its own
//! process. A future tightening (a once-cell binding shared across
//! tests, or a `serial_test`-style mutex) is the proper fix.
//!
//! Pdfium binary provisioning is documented in
//! `docs/pdfium-binary-provisioning.md`. The zero-page and encrypted
//! negative-test fixtures are generated by
//! `legacy_python_oracle/scripts/build_pdf_negative_fixtures.py`.

#![cfg(feature = "ingest")]

use std::path::{Path, PathBuf};

use cacg_ingest::{extract_pages, IngestError};
use pdfium_render::prelude::Pdfium;

/// Returns `true` when `pdfium-render` successfully binds to a system
/// `libpdfium`. When `false`, tests that exercise the live binding
/// either skip with a notice or hard-fail under `CACG_REQUIRE_PDFIUM=1`.
fn pdfium_available() -> bool {
    Pdfium::bind_to_system_library().is_ok()
}

fn parity_pdfs_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .join("tests")
        .join("parity_corpus")
        .join("pdfs")
}

fn fixture_path(name: &str) -> PathBuf {
    parity_pdfs_dir().join(name)
}

/// Returns `true` when the test should skip because libpdfium is not
/// available. Honors `CACG_REQUIRE_PDFIUM=1` as a hard-failure gate
/// so CI can refuse to silently green-light the Pdfium-bound
/// negative-test path (see `docs/pdfium-binary-provisioning.md`).
fn skip_if_pdfium_unavailable() -> bool {
    if pdfium_available() {
        return false;
    }
    assert!(
        !(std::env::var("CACG_REQUIRE_PDFIUM").as_deref() == Ok("1")),
        "CACG_REQUIRE_PDFIUM=1 set but libpdfium is not available; \
             see docs/pdfium-binary-provisioning.md for setup."
    );
    eprintln!(
        "skipping: libpdfium not available on this runner; \
         see docs/pdfium-binary-provisioning.md \
         (set CACG_REQUIRE_PDFIUM=1 to make this a hard failure)."
    );
    true
}

/// Returns `true` when the test should skip because the named fixture
/// is missing. Mirrors the libpdfium-skip ergonomics: the suite stays
/// green if a fixture is ever pruned in a fresh checkout, instead of
/// turning a missing file into an opaque panic.
fn skip_if_fixture_missing(p: &Path) -> bool {
    if p.exists() {
        return false;
    }
    eprintln!("skipping: fixture {} not found", p.display());
    true
}

#[test]
fn extract_pages_yields_thirty_nonempty_pages_for_cfa_vol1_trim() {
    if skip_if_pdfium_unavailable() {
        return;
    }
    let fixture = fixture_path("cfa_vol1_trim.pdf");
    if skip_if_fixture_missing(&fixture) {
        return;
    }
    let bytes = std::fs::read(&fixture).expect("fixture read must succeed");
    let pages = extract_pages(&bytes).expect("extraction must succeed on a valid PDF");

    assert_eq!(
        pages.len(),
        30,
        "cfa_vol1_trim.pdf is the documented 30-page trim of CFA Vol.1"
    );
    for (idx, text) in pages.iter().enumerate() {
        assert!(
            !text.trim().is_empty(),
            "page {} text must be non-empty after pdfium extraction",
            idx + 1,
        );
    }
}

/// Focused regression test for the Pdfium soft-hyphen STX → U+FFFE
/// mapping that `extract_pages_impl` applies in
/// `crates/cacg-ingest/src/pdf.rs`.
///
/// Pdfium's per-string accessor `FPDFText_GetText` (used by
/// pypdfium2) post-processes the raw soft-hyphen marker `U+0002`
/// (STX) into the non-character `U+FFFE`. The per-char accessor
/// `FPDFText_GetUnicode` (used by `text.chars().iter()` in the
/// Rust extraction path) returns the raw `U+0002`. The fix applies
/// the same transform Rust-side so the extracted text is byte-equal
/// with Python's pypdfium2 output (AC-5, Round 9).
///
/// `cfa_vol1_trim.pdf` empirically yields exactly 31 U+FFFE
/// soft-hyphen markers across its 30 pages of normalized
/// extract-layer output (Python `extract_pages_normalized` produces
/// the same count; the byte-equal post-chunker manifest has 36
/// because the chunker's overlap-carry duplicates some of those
/// chars across chunk boundaries). The byte-equal contract assumes
/// every soft-hyphen surfaces as U+FFFE in the Rust extraction
/// output; this test locks that empirical count + the absence of
/// any raw U+0002 leaking through. If a future Pdfium build changes
/// when `FPDFText_GetUnicode` emits STX, this test fails BEFORE the
/// (much more expensive) AC-5 byte-equal parity test does, giving
/// a focused diagnostic surface.
#[test]
fn extract_pages_maps_pdfium_soft_hyphen_stx_to_u_fffe() {
    if skip_if_pdfium_unavailable() {
        return;
    }
    let fixture = fixture_path("cfa_vol1_trim.pdf");
    if skip_if_fixture_missing(&fixture) {
        return;
    }
    let bytes = std::fs::read(&fixture).expect("fixture read must succeed");
    let pages = extract_pages(&bytes).expect("extraction must succeed on a valid PDF");

    let joined: String = pages.iter().cloned().collect::<String>();
    let fffe_count = joined.matches('\u{FFFE}').count();
    let stx_count = joined.matches('\u{0002}').count();

    assert_eq!(
        fffe_count, 31,
        "cfa_vol1_trim.pdf is the empirical Pdfium-soft-hyphen \
         fixture: 31 occurrences of U+FFFE are expected across the \
         30 pages of normalized extract-layer output. A drift here \
         means either the soft-hyphen mapping regressed or the \
         bundled Pdfium build changed; see \
         docs/pdfium-binary-provisioning.md.",
    );
    assert_eq!(
        stx_count, 0,
        "No raw U+0002 (STX) may leak through the extraction loop \
         — the Rust mapping at crates/cacg-ingest/src/pdf.rs must \
         rewrite every STX to U+FFFE before the page text is \
         returned. Found {stx_count} raw STX characters; the \
         mapping has regressed.",
    );
}

#[test]
fn extract_pages_rejects_truncated_pdf() {
    if skip_if_pdfium_unavailable() {
        return;
    }
    let fixture = fixture_path("cfa_vol1_trim.pdf");
    if skip_if_fixture_missing(&fixture) {
        return;
    }
    let bytes = std::fs::read(&fixture).expect("fixture read must succeed");
    // Preserve the %PDF- magic header (first 32 bytes include the
    // version line + binary marker) but drop the rest: asserts pdfium's
    // "valid magic, no body" load behavior rather than the simpler
    // "missing magic" path that the garbage-bytes test covers.
    assert!(
        bytes.len() >= 32,
        "fixture must be at least 32 bytes to preserve the magic header"
    );
    let truncated = &bytes[..32];

    match extract_pages(truncated) {
        Err(IngestError::Corrupt { detail }) => {
            assert!(
                !detail.is_empty(),
                "Corrupt diagnostic detail must be informative"
            );
        }
        other => panic!("expected IngestError::Corrupt on truncated PDF, got {other:?}"),
    }
}

#[test]
fn extract_pages_rejects_garbage_bytes() {
    if skip_if_pdfium_unavailable() {
        return;
    }
    // Bytes without a %PDF- header fail at pdfium's loader. Asserting
    // "load" in the detail string locks the intent: the rejection
    // happens at load time, not at the per-page extraction loop or
    // the zero-page guard. A future refactor that moves the rejection
    // to a different code path should re-evaluate this assertion.
    let garbage: &[u8] = b"This is not a PDF file. Just plain ASCII text.";

    match extract_pages(garbage) {
        Err(IngestError::Corrupt { detail }) => {
            assert!(
                detail.contains("load"),
                "Corrupt detail must reference the load failure path; got: {detail}"
            );
        }
        other => panic!("expected IngestError::Corrupt on garbage bytes, got {other:?}"),
    }
}

#[test]
fn extract_pages_rejects_pdf_with_no_pages() {
    if skip_if_pdfium_unavailable() {
        return;
    }
    let fixture = fixture_path("zero_pages.pdf");
    if skip_if_fixture_missing(&fixture) {
        return;
    }
    let bytes = std::fs::read(&fixture).expect("fixture read must succeed");

    // A PDF whose Pages tree carries /Count 0 /Kids [] either loads
    // and reports zero pages (caught by pdf.rs's explicit zero-page
    // guard, emitting "PDF contains zero pages") or is rejected
    // outright by pdfium (caught by pdf.rs's load-failure path,
    // emitting "pdfium load failed: ..."). Both outcomes surface as
    // IngestError::Corrupt with CACG-INGEST-001; locking the substring
    // assertion to one of those two intents catches a future regression
    // that misroutes the rejection to the per-page panic branch.
    match extract_pages(&bytes) {
        Err(IngestError::Corrupt { detail }) => {
            assert!(
                detail.contains("zero pages") || detail.contains("load"),
                "Corrupt detail must reference the zero-page or load-failure path; got: {detail}"
            );
        }
        other => panic!("expected IngestError::Corrupt on no-pages PDF, got {other:?}"),
    }
}

#[test]
fn extract_pages_rejects_encrypted_pdf() {
    if skip_if_pdfium_unavailable() {
        return;
    }
    let fixture = fixture_path("encrypted.pdf");
    if skip_if_fixture_missing(&fixture) {
        return;
    }
    let bytes = std::fs::read(&fixture).expect("fixture read must succeed");

    // The Standard security handler verifies the user password by
    // hashing the supplied password (empty when extract_pages passes
    // None) and comparing to the /U entry. The fixture's /U is all
    // zeros, which no real password hashes to, so pdfium rejects the
    // document at password verification before any decryption is
    // attempted. The rejection routes through pdf.rs's load-failure
    // branch ("pdfium load failed: ...") and surfaces as
    // IngestError::Corrupt with CACG-INGEST-001.
    match extract_pages(&bytes) {
        Err(IngestError::Corrupt { detail }) => {
            assert!(
                detail.contains("load"),
                "Corrupt detail must reference the load-failure path; got: {detail}"
            );
        }
        other => panic!("expected IngestError::Corrupt on encrypted PDF, got {other:?}"),
    }
}
