#![allow(clippy::unwrap_used)]
//! AC-C2 byte-equal parity gate: load `tests/parity_corpus/out_python/hash_oracles.json`
//! and assert `cacg_core::hash::{source_sha256, chunk_hash, card_hash,
//! compute_event_checksum}` produces byte-identical output to the Python-
//! computed `expected` values across every committed corpus fixture.
//!
//! The hash oracle is generated by `legacy_python_oracle/scripts/build_hash_oracles.py` and
//! wired into `legacy_python_oracle/scripts/build_parity_corpus.py` as a final Phase 8 step,
//! so the file stays in sync with the M0 corpus on any regeneration.
//!
//! Plan reference: AC-C2 at
//! `plans/cacg-rust-port-trust-kernel-first-plan.md:58`.

use std::path::PathBuf;

use cacg_core::canonical_json::canonical_json;
use cacg_core::hash::{card_hash, chunk_hash, compute_event_checksum, source_sha256, PageSpan};
use serde_json::Value;

fn workspace_root() -> PathBuf {
    let mut p = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    p.pop();
    p.pop();
    p
}

fn load_oracle() -> Value {
    let p = workspace_root().join("tests/parity_corpus/out_python/hash_oracles.json");
    assert!(p.is_file(), "hash_oracles.json missing: {}", p.display());
    let raw = std::fs::read_to_string(&p).unwrap();
    serde_json::from_str(&raw).unwrap()
}

#[test]
fn source_sha256_matches_python() {
    let oracle = load_oracle();
    let entries = oracle["source_sha256"]
        .as_array()
        .expect("source_sha256 must be an array");
    assert!(
        !entries.is_empty(),
        "expected at least one source_sha256 entry"
    );
    let mut failures: Vec<String> = Vec::new();
    for entry in entries {
        let rel_path = entry["path"].as_str().unwrap();
        let expected = entry["expected"].as_str().unwrap();
        let abs_path = workspace_root().join(rel_path);
        assert!(
            abs_path.is_file(),
            "source file missing: {}",
            abs_path.display()
        );
        let bytes = std::fs::read(&abs_path).unwrap();
        let actual = source_sha256(&bytes);
        if actual != expected {
            failures.push(format!(
                "source_sha256 mismatch for {rel_path}: expected {expected}, got {actual}"
            ));
        }
    }
    assert!(
        failures.is_empty(),
        "failures:\n  {}",
        failures.join("\n  ")
    );
}

#[test]
fn chunk_hash_matches_python() {
    let oracle = load_oracle();
    let entries = oracle["chunk_hash"]
        .as_array()
        .expect("chunk_hash must be an array");
    assert!(
        entries.len() >= 2,
        "expected at least 2 chunk_hash entries (the sample.pdf chunks)"
    );
    let mut failures: Vec<String> = Vec::new();
    for entry in entries {
        let chunk_id = entry["chunk_id"].as_str().unwrap();
        let text = entry["text"].as_str().unwrap();
        let start_page = entry["start_page"].as_i64().unwrap();
        let end_page = entry["end_page"].as_i64().unwrap();
        let expected = entry["expected"].as_str().unwrap();
        let spans: Vec<PageSpan> = entry["page_spans"]
            .as_array()
            .unwrap()
            .iter()
            .map(|s| PageSpan {
                page: s["page"].as_i64().unwrap(),
                byte_offset_in_chunk: s["byte_offset_in_chunk"].as_i64().unwrap(),
            })
            .collect();
        let actual =
            chunk_hash(text, start_page, end_page, &spans).expect("chunk_hash returned an error");
        if actual != expected {
            failures.push(format!(
                "chunk_hash mismatch for {chunk_id}: expected {expected}, got {actual}"
            ));
        }
    }
    assert!(
        failures.is_empty(),
        "failures:\n  {}",
        failures.join("\n  ")
    );
}

#[test]
fn card_hash_matches_python() {
    // Codex R13 Mainline Gap 2: enforce EXACT per-category counts for
    // the committed corpus. The plan's AC-D2 / AC-C2 requirement is
    // exactly 5 valid + 54 unicode_edge + 12 adversarial = 71 entries.
    // Loose `>=` thresholds let a future regression replace adversarial
    // entries with extra valid entries while still hitting a total
    // threshold; exact counts close that gap.
    const REQUIRED_VALID: usize = 5;
    const REQUIRED_UNICODE_EDGE: usize = 54;
    const REQUIRED_ADVERSARIAL: usize = 12;
    const KNOWN_CATEGORIES: &[&str] = &["valid", "unicode_edge", "adversarial"];

    let oracle = load_oracle();
    let entries = oracle["card_hash"]
        .as_array()
        .expect("card_hash must be an array");

    let mut counts: std::collections::BTreeMap<String, usize> = std::collections::BTreeMap::new();
    let mut unknown_categories: Vec<String> = Vec::new();
    for entry in entries {
        let category = entry["category"]
            .as_str()
            .expect("each entry has a `category`");
        if !KNOWN_CATEGORIES.contains(&category) {
            unknown_categories.push(format!(
                "card_path {:?}: unknown category {category:?} (expected one of {KNOWN_CATEGORIES:?})",
                entry["card_path"].as_str().unwrap_or("?")
            ));
        }
        *counts.entry(category.to_string()).or_default() += 1;
    }
    assert!(
        unknown_categories.is_empty(),
        "{} unknown category entries:\n  {}",
        unknown_categories.len(),
        unknown_categories.join("\n  ")
    );
    let category_summary: Vec<String> = counts.iter().map(|(k, v)| format!("{k}={v}")).collect();
    assert_eq!(
        *counts.get("valid").unwrap_or(&0),
        REQUIRED_VALID,
        "expected EXACTLY {REQUIRED_VALID} valid entries; got counts={category_summary:?}"
    );
    assert_eq!(
        *counts.get("unicode_edge").unwrap_or(&0),
        REQUIRED_UNICODE_EDGE,
        "expected EXACTLY {REQUIRED_UNICODE_EDGE} unicode_edge entries; got counts={category_summary:?}"
    );
    assert_eq!(
        *counts.get("adversarial").unwrap_or(&0),
        REQUIRED_ADVERSARIAL,
        "expected EXACTLY {REQUIRED_ADVERSARIAL} adversarial entries; got counts={category_summary:?}"
    );

    // Codex Round-12 R12-REVIEW-1: any `skip_reason` in an adversarial
    // (or any) entry fails the test. The strict YAML loader must succeed
    // on all 12 adversarial fixtures.
    let mut failures: Vec<String> = Vec::new();
    let mut tested = 0usize;
    for entry in entries {
        let card_path = entry["card_path"].as_str().unwrap();
        let category = entry["category"].as_str().unwrap();
        if let Some(reason) = entry.get("skip_reason").and_then(|v| v.as_str()) {
            failures.push(format!(
                "card_path {card_path} ({category}) silently skipped via skip_reason {reason:?}; \
                 the strict frontmatter loader must succeed on every \
                 committed adversarial fixture (Codex R12-REVIEW-1)"
            ));
            continue;
        }
        // Codex R13 Mainline Gap 2: per-entry field-completeness gate.
        // Each non-skipped entry must carry `frontmatter` (object),
        // `raw_body` (string), and `expected` (string). A regression
        // that drops any field is now a documented test failure
        // rather than a silent panic on unwrap.
        let Some(frontmatter) = entry["frontmatter"].as_object() else {
            failures.push(format!(
                "card_path {card_path} ({category}): missing or non-object `frontmatter` field"
            ));
            continue;
        };
        let Some(raw_body) = entry["raw_body"].as_str() else {
            failures.push(format!(
                "card_path {card_path} ({category}): missing or non-string `raw_body` field"
            ));
            continue;
        };
        let Some(expected) = entry["expected"].as_str() else {
            failures.push(format!(
                "card_path {card_path} ({category}): missing or non-string `expected` field"
            ));
            continue;
        };
        let actual = card_hash(frontmatter, raw_body).expect("card_hash returned an error");
        if actual != expected {
            let fm_canonical =
                canonical_json(&Value::Object(frontmatter.clone())).unwrap_or_default();
            failures.push(format!(
                "card_hash mismatch for {card_path} ({category}): expected {expected}, got {actual}\n  \
                 frontmatter_canonical={fm_canonical}\n  \
                 raw_body_first_80_chars={raw_body:.80}"
            ));
        }
        tested += 1;
    }
    assert!(
        failures.is_empty(),
        "{} of {tested} card_hash entries failed [counts={:?}]:\n  {}",
        failures.len(),
        category_summary,
        failures.join("\n  ")
    );
}

#[test]
fn event_checksum_matches_python() {
    let oracle = load_oracle();
    let entries = oracle["event_checksum"]
        .as_array()
        .expect("event_checksum must be an array");
    assert!(
        !entries.is_empty(),
        "expected at least one event_checksum entry"
    );
    let mut failures: Vec<String> = Vec::new();
    for entry in entries {
        let history_file = entry["history_file"].as_str().unwrap();
        let line_no = entry["line_no"].as_i64().unwrap();
        let payload = entry["payload"]
            .as_object()
            .expect("payload must be an object");
        let expected = entry["expected"].as_str().unwrap();
        let actual =
            compute_event_checksum(payload).expect("compute_event_checksum returned an error");
        if actual != expected {
            failures.push(format!(
                "event_checksum mismatch at {history_file}:{line_no}: expected {expected}, got {actual}"
            ));
        }
    }
    assert!(
        failures.is_empty(),
        "failures:\n  {}",
        failures.join("\n  ")
    );
}
